In [ ]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv(r"C:\Users\Admin\Documents\Python_ACMEGRADE\Customer Segmentation\Cust_Segmentation.csv")

In [ ]:
df.head()

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0            1   41    2               6      19      0.124       1.073   
1            2   47    1              26     100      4.582       8.218   
2            3   33    2              10      57      6.111       5.802   
3            4   29    2               4      19      0.681       0.516   
4            5   47    1              31     253      9.308       8.908   

   Defaulted Address  DebtIncomeRatio  
0        0.0  NBA001              6.3  
1        0.0  NBA021             12.8  
2        1.0  NBA013             20.9  
3        0.0  NBA009              6.3  
4        0.0  NBA008              7.2

In [ ]:
df.describe()

Customer Id         Age         Edu  Years Employed      Income  \
count    850.00000  850.000000  850.000000      850.000000  850.000000   
mean     425.50000   35.029412    1.710588        8.565882   46.675294   
std      245.51816    8.041432    0.927784        6.777884   38.543054   
min        1.00000   20.000000    1.000000        0.000000   13.000000   
25%      213.25000   29.000000    1.000000        3.000000   24.000000   
50%      425.50000   34.000000    1.000000        7.000000   35.000000   
75%      637.75000   41.000000    2.000000       13.000000   55.750000   
max      850.00000   56.000000    5.000000       33.000000  446.000000   

        Card Debt  Other Debt   Defaulted  DebtIncomeRatio  
count  850.000000  850.000000  700.000000       850.000000  
mean     1.576820    3.078773    0.261429        10.171647  
std      2.125843    3.398799    0.439727         6.719441  
min      0.012000    0.046000    0.000000         0.100000  
25%      0.382500    1.045750    0.000000         5.100000  
50%      0.885000    2.003000    0.000000         8.700000  
75%      1.898500    3.903250    1.000000        13.800000  
max     20.561000   35.197000    1.000000        41.300000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Customer Id      850 non-null    int64  
 1   Age              850 non-null    int64  
 2   Edu              850 non-null    int64  
 3   Years Employed   850 non-null    int64  
 4   Income           850 non-null    int64  
 5   Card Debt        850 non-null    float64
 6   Other Debt       850 non-null    float64
 7   Defaulted        700 non-null    float64
 8   Address          850 non-null    object 
 9   DebtIncomeRatio  850 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 66.5+ KB


In [ ]:
df.shape

(850, 10)

In [ ]:
df=df.drop('Address',axis=1)

In [ ]:
df

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0              1   41    2               6      19      0.124       1.073   
1              2   47    1              26     100      4.582       8.218   
2              3   33    2              10      57      6.111       5.802   
3              4   29    2               4      19      0.681       0.516   
4              5   47    1              31     253      9.308       8.908   
..           ...  ...  ...             ...     ...        ...         ...   
845          846   27    1               5      26      0.548       1.220   
846          847   28    2               7      34      0.359       2.021   
847          848   25    4               0      18      2.802       3.210   
848          849   32    1              12      28      0.116       0.696   
849          850   52    1              16      64      1.866       3.638   

     Defaulted  DebtIncomeRatio  
0          0.0              6.3  
1          0.0             12.8  
2          1.0             20.9  
3          0.0              6.3  
4          0.0              7.2  
..         ...              ...  
845        NaN              6.8  
846        0.0              7.0  
847        1.0             33.4  
848        0.0              2.9  
849        0.0              8.6  

[850 rows x 9 columns]

In [ ]:
import numpy as np
df.replace("?",np.nan,inplace=True)


In [ ]:
avg_Defaulted=df["Defaulted"].mean()
df["Defaulted"].replace(np.nan,avg_Defaulted,inplace=True)

In [ ]:
df.shape

(850, 9)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X=df.values[:,1:]



In [ ]:
X

array([[41.   ,  2.   ,  6.   , ...,  1.073,  0.   ,  6.3  ],
       [47.   ,  1.   , 26.   , ...,  8.218,  0.   , 12.8  ],
       [33.   ,  2.   , 10.   , ...,  5.802,  1.   , 20.9  ],
       ...,
       [25.   ,  4.   ,  0.   , ...,  3.21 ,  1.   , 33.4  ],
       [32.   ,  1.   , 12.   , ...,  0.696,  0.   ,  2.9  ],
       [52.   ,  1.   , 16.   , ...,  3.638,  0.   ,  8.6  ]])

In [ ]:
X2=np.nan_to_num(X)

In [ ]:
# Scalling Operatio Z Score

In [ ]:
X3=sklearn.preprocessing.StandardScaler().fit_transform(X)

In [ ]:
X3

array([[ 0.74291541,  0.31212243, -0.37878978, ..., -0.59048916,
        -0.65560267, -0.57652509],
       [ 1.48949049, -0.76634938,  2.5737211 , ...,  1.51296181,
        -0.65560267,  0.39138677],
       [-0.25251804,  0.31212243,  0.2117124 , ...,  0.80170393,
         1.85216712,  1.59755385],
       ...,
       [-1.24795149,  2.46906604, -1.26454304, ...,  0.03863257,
         1.85216712,  3.45892281],
       [-0.37694723, -0.76634938,  0.50696349, ..., -0.70147601,
        -0.65560267, -1.08281745],
       [ 2.1116364 , -0.76634938,  1.09746566, ...,  0.16463355,
        -0.65560267, -0.2340332 ]])

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
clf=KMeans(n_clusters=3, init='k-means++', n_init=10, max_iter=300)

In [ ]:
clf.fit(X3)

KMeans(n_clusters=3)

In [ ]:
clf.labels_

array([2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2,
       0, 1, 1, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 1, 0, 1,
       2, 1, 2, 2, 2, 2, 1, 1, 0, 2, 0, 0, 0, 2, 2, 2, 1, 2, 1, 1, 2, 2,
       2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 1, 2, 0, 2,
       0, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 2, 0, 0, 1, 2, 2, 2, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       2, 2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 0,
       2, 2, 0, 1, 0, 2, 2, 1, 0, 0, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 1,
       1, 2, 1, 2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2,
       0, 1, 2, 2, 2, 2, 1, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 0, 2, 2, 2, 0, 2, 0,
       1, 0, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 2, 1, 2,
       1, 2, 2, 1, 2, 2, 2, 0, 2, 2, 0, 2, 0, 1, 2,

In [ ]:
df["Final"]=clf.labels_

In [ ]:
df

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0              1   41    2               6      19      0.124       1.073   
1              2   47    1              26     100      4.582       8.218   
2              3   33    2              10      57      6.111       5.802   
3              4   29    2               4      19      0.681       0.516   
4              5   47    1              31     253      9.308       8.908   
..           ...  ...  ...             ...     ...        ...         ...   
845          846   27    1               5      26      0.548       1.220   
846          847   28    2               7      34      0.359       2.021   
847          848   25    4               0      18      2.802       3.210   
848          849   32    1              12      28      0.116       0.696   
849          850   52    1              16      64      1.866       3.638   

     Defaulted  DebtIncomeRatio  Final  
0     0.000000              6.3      2  
1     0.000000             12.8      1  
2     1.000000             20.9      0  
3     0.000000              6.3      2  
4     0.000000              7.2      1  
..         ...              ...    ...  
845   0.261429              6.8      2  
846   0.000000              7.0      2  
847   1.000000             33.4      0  
848   0.000000              2.9      2  
849   0.000000              8.6      1  

[850 rows x 10 columns]

In [ ]:
df.groupby('Final').mean()

Customer Id        Age       Edu  Years Employed      Income  \
Final                                                                 
0       419.635359  31.491713  1.939227        3.895028   32.408840   
1       431.774648  43.450704  1.901408       17.528169  103.478873   
2       425.823529  33.975332  1.580645        7.755218   36.269450   

       Card Debt  Other Debt  Defaulted  DebtIncomeRatio  
Final                                                     
0       1.709017    2.946707   0.923410        14.388398  
1       4.174197    8.059282   0.185352        13.746479  
2       0.831554    1.782135   0.054568         7.760152

In [ ]:
plt.sctater(X3[])